server { listen 80; client_max_body_size 1024m;
  location /api/ { proxy_pass http://api:4000/; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
  location / { proxy_pass http://web:3000; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; }
}
